Update validate-all-test-cases.yaml
debugging -s (take 2)

diff --git a/.github/workflows/validate-all-test-cases.yaml b/.github/workflows/validate-all-test-cases.yaml
--- a/.github/workflows/validate-all-test-cases.yaml
+++ b/.github/workflows/validate-all-test-cases.yaml
@@ -91,8 +91,8 @@ jobs:
              -ed ".svn,.git" \
              -rf "${REPORT_DIR}/temp_report_${util}.txt" \
              -rft "txt" \
-             -s \
-             -u
+             -schema \
+             -resolve-url || echo "Validation failed for $util"
             
             # Combine results to main report if temp report exists
             if [ -f "${REPORT_DIR}/temp_report_${util}.txt" ]; then
